name: Build Android APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码(包含子模块)
        uses: actions/checkout@v4
        with:
          submodules: recursive # 自动拉取依赖的子项目
          fetch-depth: 0

      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # 开启缓存，下次编译更快

      - name: 赋予执行权限
        run: chmod +x gradlew

      - name: 开始编译
        # 增加 --stacktrace 参数，如果失败会显示更详细的报错
        run: ./gradlew assembleDebug --stacktrace
        
      - name: 上传 APK
        if: success() # 只有成功时才上传
        uses: actions/upload-artifact@v4
        with:
          name: ONO-App-Package
          path: app/build/outputs/apk/debug/*.apk
